### ISSUE TITLE
Single pixel color

### ISSUE THREAD

**Issue by pknmax** [graphdeco-inria/diff-gaussian-rasterization#29]
hello @kwea123 @Snosixtyboo @grgkopanas,
I am interested in getting final color at particular location for different view directions, by providing 3DGS pointcloud, location of target pixel for tracking in first fully rasterized image using first colmap camera pose from colmap pose sequence or 3D location in scene (how to find it?), and colmap camera poses.
Can you please guide me to achieve this?

**Comment by pknmax** [comment]
@kewa @Snosixtyboo

**Comment by hariharan1412** [comment]
Hey Hi, Did you actually figured out a way to achieve this ?

**Comment by pknmax** [comment]
not really, check this comment [#597](https://github.com/graphdeco-inria/gaussian-splatting/issues/597#issuecomment-1936723642)
