### ISSUE TITLE
Debugging the project

### ISSUE THREAD

**Issue by VladimirYugay** [graphdeco-inria/diff-gaussian-rasterization#34]
I want to debug the cuda kernels. I've prepared a data checkpoint for debugging. However, I'm not sure how to configure Cmake to make it work. 

For now, I tried adding a `main.cpp` which includes `rasterize_points.h`, and use the following cmake:

```
cmake_minimum_required(VERSION 3.20)
project(TestProject LANGUAGES CXX CUDA)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CUDA_STANDARD 17)

# List your CUDA source files here
set(CUDA_SOURCES
    cuda_rasterizer/backward.h
    cuda_rasterizer/backward.cu
    cuda_rasterizer/forward.h
    cuda_rasterizer/forward.cu
    cuda_rasterizer/auxiliary.h
    cuda_rasterizer/rasterizer_impl.cu
    cuda_rasterizer/rasterizer_impl.h
    cuda_rasterizer/rasterizer.h)

# Create an executable that includes both your main.cpp and CUDA source files
add_executable(test_executable main.cpp ${CUDA_SOURCES})

# Specify CUDA architectures (adjust as needed)
set_target_properties(test_executable PROPERTIES CUDA_ARCHITECTURES "70;75;86")

# Include directories, if you have any
target_include_directories(test_executable PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/cuda_rasterizer)
target_include_directories(test_executable PRIVATE third_party/glm ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES})
target_include_directories(test_executable PRIVATE ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES})

# Link with CUDA libraries if needed
target_link_libraries(test_executable PRIVATE cuda)
```

I create `build`, and call `cmake ..`, but get an error:

`CUDA_ARCHITECTURES is empty for target "cmTC_73c6d".`

I assume I missed some additional flags, since I'm able to install the project via `pip`.

**Comment by penguinflys** [comment]
Hi @VladimirYugay , did you make it to debug? Can you please share your method for debugging?

**Comment by VladimirYugay** [comment]
Took me quite some time.

1. Add main.cpp to the project, and compile it all together, that would be your starting debugging point. For this you'd need to adjust cmake significantly, but it's system-dependent
2. Save the dump before and after forward/backward in the __init__.py of the repo
3. Unpack those to the tensors in C++ using libtorch
4. Run rasterize_points from cmake with the arguments that you unpacked

**Comment by penguinflys** [comment]
Thanks a lot, it is very helpful.

**Comment by MobiusLqm** [comment]
> Took me quite some time.
> 
> 1. Add main.cpp to the project, and compile it all together, that would be your starting debugging point. For this you'd need to adjust cmake significantly, but it's system-dependent
> 2. Save the dump before and after forward/backward in the **init**.py of the repo
> 3. Unpack those to the tensors in C++ using libtorch
> 4. Run rasterize_points from cmake with the arguments that you unpacked

hi！ thank you for your reply, could you please share your codes for dubuging?  
Sincerely Thanks if you could helps me!

**Comment by VladimirYugay** [comment]
@MobiusLqm, sure, you can find it [here](https://github.com/VladimirYugay/gaussian_rasterizer)

**Comment by MobiusLqm** [comment]
I really appreciate your support very much @VladimirYugay

**Comment by steezera** [comment]
hi @VladimirYugay , First of all, thank you for all this great work. I was trying to debug rasterizer like you and I'm really glad to find your comment. But I think your cMakeLists.txt is written on ubuntu i guess, and here is my question : To debug on Windows, is tweaking the CMakeLists.txt file enough, or should I rebuild the entire build folder as well? Hope to get your help, thank you.

**Comment by VladimirYugay** [comment]
Hey @steezera. You are right, it is for the Linux setup. I'm personally unaware of how to exactly compile it for Windows. 

However, I think the process might be quite similar since it is still the same code. To do this you need to tweak the [CMakeLists.txt](https://github.com/VladimirYugay/gaussian_rasterizer/blob/master/CMakeLists.txt) such that `cmake ..` would successfully finish and there are no warnings like `didn't find the pybind` or similar and then call `make` in the build folder just as described in the readme.

In case you succeed, please open a PR, that might be helpful for others. Thanks!
