### ISSUE TITLE
Diagonal scaling matrix get incorrectly initialized to a full-one matrix

### ISSUE THREAD

**Issue by Mistariano** [graphdeco-inria/diff-gaussian-rasterization#37]
Hi guys,

I wonder that ths S matrix defined in `computeCov3D` funcs for both fwd/bwd computations is now incorrectly initialized to full-one:
https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/forward.cu#L121

If I understand correctly, here we expect an identity matrix instead:
```
glm::mat3 S = glm::mat3(
    1.0f, 0.0f, 0.0f,
    0.0f, 1.0f, 0.0f,
    0.0f, 0.0f, 1.0f
);
```
Fortunately, such a full-one matrix with a scaled main diagonal is usually positively defined and symmetric. Thus, the reparameterized $R^TSSR$ is still a covariance matrix.

I have roughly checked that this issue is not so influential to the PSNR performance. If required and agreed, I'm more than glad to submit a hotfix PR for it.

**Comment by ys-koshelev** [comment]
@Mistariano Please beware, that according to the [Sec. 5.4.2 of OpenGL API docs](https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.20.pdf)

> If there is a single scalar parameter to a vector constructor, it is used to initialize all components of the constructed vector to that scalar’s value. If there is a single scalar parameter to a matrix constructor, it is used to initialize all the components on the matrix’s diagonal, with the remaining components initialized to 0.0.

For this reason, `glm::mat3 S = glm::mat3(1.0f);` provides identity matrix, not the matrix full of ones.

**Comment by Mistariano** [comment]
@ys-koshelev Thanks a lot for your kind reply. I will close this issue.
