### ISSUE TITLE
my_radius calculation

### ISSUE THREAD

**Issue by ibreathebsb** [graphdeco-inria/diff-gaussian-rasterization#39]
https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/forward.cu#L232C1-L233C1

I'm trying to understand above code snipet,if it's 3-sigma rule,shouldn't it be:
```cuda
float my_radius = ceil(sqrt(3.0f * max(lambda1, lambda2)));
```

**Comment by loryruta** [comment]
I'm trying to understand `my_radius` calculation too, have you figured it out?

To my understanding, given the conic matrix, the radii should be the reciprocal of the eigenvalues' sqrt:
https://en.wikipedia.org/wiki/Ellipsoid#As_a_quadric

Whatever the above calculation is, they're skipping the inverse. Also I expect `my_radius` to be in NDC space (`[-1, 1]` `[0, 1]` or whatever) but they use it as if it were in screen space (i.e. `[width, height]`).
